### ISSUE TITLE
stuck on blocked

### ISSUE THREAD

**Issue by jamesbeedy** [tengu-team/layer-ssl-termination-proxy#11]
No matter what I do I can't seem to get past this blocked state .... hmmmm

```bash
Model     Controller  Cloud/Region   Version  SLA
owncloud  pdl-aws     aws/us-west-2  2.3.2    unsupported

App         Version  Status   Scale  Charm                  Store       Rev  OS      Notes
owncloud             active       1  owncloud               jujucharms    3  ubuntu
postgresql  9.5.10   active       1  postgresql             jujucharms  165  ubuntu
ssl-proxy            blocked      1  ssl-termination-proxy  jujucharms    9  ubuntu  exposed

Unit           Workload  Agent  Machine  Public address  Ports           Message
owncloud/0*    active    idle   0        172.31.104.216  80/tcp          Owncloud available at http://owncloud.peopledatalabs.com/owncloud
postgresql/0*  active    idle   1        172.31.102.45   5432/tcp        Live master (9.5.10)
ssl-proxy/1*   blocked   idle   3        54.149.189.130  80/tcp,443/tcp  Please relate an HTTP webservice (registered owncloud.peopledatalabs.com)

Machine  State    DNS             Inst id              Series  AZ          Message
0        started  172.31.104.216  i-008400abec551f50d  xenial  us-west-2c  running
1        started  172.31.102.45   i-0cc7a0637858fbeb9  xenial  us-west-2a  running
3        started  54.149.189.130  i-0791fea567f943ce4  xenial  us-west-2c  running

Relation provider       Requirer                Interface    Type     Message
owncloud:http           ssl-proxy:reverseproxy  http         regular
postgresql:coordinator  postgresql:coordinator  coordinator  peer
postgresql:db           owncloud:postgresql     pgsql        regular
postgresql:replication  postgresql:replication  pgpeer       peer

```

**Comment by jamesbeedy** [comment]
here is my bundle
```yaml
series: xenial
applications:
  postgresql:
    charm: 'cs:postgresql'
    num_units: 1
  owncloud:
    charm: 'cs:~omnivector/owncloud'
    num_units: 1
    options:
      fqdn: 'owncloud.peopledatalabs.com'
  ssl-proxy:
    charm: 'cs:~tengu-team/ssl-termination-proxy-9'
    num_units: 1
relations:
  - - 'postgresql:db'
    - 'owncloud:postgresql'
  - - 'owncloud:http'
    - 'ssl-proxy:reverseproxy'
```
